In [3]:
!pip install gym

  Running setup.py bdist_wheel for gym: started
  Running setup.py bdist_wheel for gym: finished with status 'done'
  Stored in directory: C:\Users\Y.G JI\AppData\Local\pip\Cache\wheels\ad\46\5a\1833d0ef8149a50e78fdb24a41f47e22a7f4a9dcd649b8db53
Successfully built gym


You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [2]:
import gym

In [3]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt 

In [5]:
from gym.envs.registration import register
import random as pr

In [6]:
def rargmax(vector):
    m = np.amax(vector)
    indices = np.nonzero(vector == m)[0]
    return pr.choice(indices)

In [7]:
register(
    id='FrozenLake-v3',
    entry_point = 'gym.envs.toy_text:FrozenLakeEnv',
    kwargs={'map_name':'4x4',
            'is_slippery' : False}
)
env = gym.make('FrozenLake-v3')

In [ ]:
env

In [8]:
Q = np.zeros([env.observation_space.n,env.action_space.n])
dis = .99
num_episodes = 20

rList = []

for i in range(num_episodes) :
    state = env.reset()
    rAll = 0
    done = False
    #e=1./((i//100)+1)
    while not done :

        #if np.random.rand(1)<e:
        #    action = rargmax(Q[state,:] + np.random.randn(1,env.action_space.n)/(i+1))
        #else:
        #    action = np.argmax(Q[state, :])

        action = rargmax( Q[state,:] )
        new_state, reward, done,_ = env.step(action)

        Q[state,action] = reward + dis * np.max(Q[new_state,:])

        rAll += reward
        state = new_state

    rList.append(rAll)


In [9]:
print("Sucess rate" + str(sum(rList)/num_episodes))
print("Final Q-Table Values")
print("LEFT DOWN RIGHT UP")
print(Q)
plt.bar(range(len(rList)),rList,color = "blue")
plt.show()

Sucess rate0.0
Final Q-Table Values
LEFT DOWN RIGHT UP
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
