In [4]:
import numpy 
import datetime

In [20]:
rnorm = numpy.random.normal(1100,  50,  10)

In [21]:
rnorm[0]

1181.5099740089679

In [7]:
startDatetime = datetime.datetime.strptime('2015-04-15 00:00:00', '%Y-%m-%d %H:%M:%S')
startDatetime

datetime.datetime(2015, 4, 15, 0, 0)

In [74]:
nextDatetime = startDatetime + datetime.timedelta(seconds=1)
nextDatetime

datetime.datetime(2015, 4, 15, 0, 0, 1)

In [18]:
dateStr = nextDatetime.strftime('%Y-%m-%d')
dateStr

'2015-04-15'

In [19]:
timeStr = nextDatetime.strftime('%H:%M:%S')
timeStr

'00:00:01'

In [ ]:
## 특정시점으로부터 1초마다 정규분포( 평균=100, 분산=10)인 50개의 데이터 생성
startStr = "2015-04-15 00:00:00"
sec = 1
N = 50
mu = 100
sigma = 10

nextDatetime = datetime.datetime.strptime(startStr, '%Y-%m-%d %H:%M:%S')
randData1 = numpy.random.normal(mu,  sigma,  N)

for i in range(N):
    dateStr = nextDatetime.strftime('%Y-%m-%d')
    timeStr = nextDatetime.strftime('%H:%M:%S')
    rnum = randData1[ i ] 
    print ( "%s, %s, %d " %( dateStr, timeStr, rnum )  )
    nextDatetime = nextDatetime + datetime.timedelta(seconds=sec)

In [26]:
## 정규분포 함수를 인자로 넘겨주고, 평균과 분산도 인자로..
def randomDistirbute( mean, sigma, size, distributeFun ) :
    return distributeFun( mean, sigma, size )
    
randomDistirbute( 0, 2, 10, numpy.random.normal  ) 

array([-0.79597308,  1.52027732, -1.51210882, -4.66201306, -2.14888   ,
       -0.24532517,  1.02183417,  0.01168497, -0.94490873,  0.83707018])

In [27]:
randomDistirbute( 10, 1, 10, numpy.random.normal  ) 

array([ 10.63954788,   9.48491327,   9.05405492,  11.83210664,
         9.31149147,   8.9824002 ,  10.97576266,  10.05663445,
        12.50187172,   8.06960552])

In [38]:
funStr = numpy.random.normal
#print funStr.__class__
print funStr.__name__
#print funStr.__doc__


normal


In [59]:
## 여러가지 분포에 따라서 인자 설정을 다르게 처리함.
def randomDistribute( mean, sigma, size, distributeFun ) :
    if "poisson" == distributeFun.__name__ : 
        return distributeFun( mean, size )
    else :
        return distributeFun( mean, sigma, size )

In [61]:
randomDistribute( 5, 2, 10, numpy.random.normal  ) 

array([ 8.72539553,  4.20342648,  4.73180546,  2.39391589,  5.19780368,
        6.99349119,  6.00779281,  6.82954564,  2.93021044,  6.23875417])

In [62]:
randomDistribute( 5, 2, 10, numpy.random.poisson  ) 

array([7, 5, 8, 3, 4, 2, 6, 5, 7, 4])

In [63]:
randomDistribute( 5, 2, 10, numpy.random.uniform  ) 

array([ 2.80049233,  2.98609819,  4.18510226,  3.44758605,  4.52820942,
        2.01512886,  3.78018997,  2.89498066,  2.71886338,  2.95574606])

In [64]:
randomDistribute( 100, 2, 10, numpy.random.lognormal  ) 

array([  3.52205923e+44,   6.95919288e+41,   5.57978871e+42,
         3.60469010e+41,   5.51937841e+42,   7.67980187e+43,
         1.19645704e+45,   1.22540120e+43,   1.13812744e+44,
         3.67033554e+43])

## 여러가지 센서와 해당 센서가 갖는 분포를 정의함.

In [87]:
sensor01 = {'code':'1', 'desc': 'Temerature' ,'mu':1100, 'sigma': 50, 'distribute' : numpy.random.normal }
sensor02 = {'code':'2', 'desc': 'Humidity'   ,'mu':62,   'sigma': 5,  'distribute' : numpy.random.normal }
sensor03 = {'code':'3', 'desc': 'Speed'      ,'mu':225,  'sigma': 0,  'distribute' : numpy.random.poisson }
sensor04 = {'code':'4', 'desc': 'Vibration'  ,'mu':550,  'sigma': 10, 'distribute' : numpy.random.normal }
sensor05 = {'code':'5', 'desc': 'Pressure'   ,'mu':300,  'sigma': 400,'distribute' : numpy.random.uniform }
sensor06 = {'code':'6', 'desc': 'Noise'      ,'mu':65,   'sigma': 10, 'distribute' : numpy.random.poisson }

In [88]:
allSensor = list()
allSensor.append( sensor01 ) 
allSensor.append( sensor02 ) 
allSensor.append( sensor03 ) 
allSensor.append( sensor04 ) 
allSensor.append( sensor05 ) 
allSensor.append( sensor06 ) 

for sens in allSensor:
    print 'code=%s, desc=%s' %( sens['code'], sens['code'] )

code=1, desc=1
code=2, desc=2
code=3, desc=3
code=4, desc=4
code=5, desc=5
code=6, desc=6


## 여러가지 센서 정보를 설정하고 특정시점부터 데이터를 N개 생성하는 함수 정의

In [93]:
def makeSensorData( SensorList, currDateTime, sec, N ) :
    """ 여러가지 센서 정보를 인자로 받고 특정시점부터 데이터를 N개 생성하는 함수 정의
    SensorList : 센서 정보를 갖는 List, 센서 정보를 dictionary형식으로 정의함.
    currDateTime : 특정시점 
    sec : 시간 간격(초)
    N : 생성할 데이터의 개수
    """
    from cStringIO import StringIO
    strIO = StringIO()
    
    codeList = list()
    randNumList = list()
    for sensor in SensorList :
        codeList.append( sensor['code'] )
        rnum = randomDistribute( 
            sensor['mu'], 
            sensor['sigma'], 
            N, 
            sensor['distribute']  ) 
        randNumList.append( rnum )

    for i in range( N ) :
        dateStr = currDateTime.strftime('%Y-%m-%d')
        timeStr = currDateTime.strftime('%H:%M:%S')
        for idx in range( len(codeList) ) : 
            strIO.write( "%s,%s,%s,%d\n" %( dateStr, timeStr, codeList[idx], randNumList[idx][i] )  )
            
        currDateTime = currDateTime + datetime.timedelta(seconds=sec)        
    return strIO.getvalue()    

In [95]:
makeSensorData( allSensor, nextDatetime, 1, 1)

'2015-04-15,00:00:01,1,1119\n2015-04-15,00:00:01,2,48\n2015-04-15,00:00:01,3,188\n2015-04-15,00:00:01,4,561\n2015-04-15,00:00:01,5,359\n2015-04-15,00:00:01,6,68\n'

In [96]:
with open('output.txt', 'w') as file:
    aa = makeSensorData( allSensor, nextDatetime, 1, 1)
    file.write( aa )
    aa = makeSensorData( allSensor, nextDatetime, 1, 1)
    file.write( aa )
    aa = makeSensorData( allSensor, nextDatetime, 1, 1)
    file.write( aa )    

In [103]:
7 % 8

7

In [37]:
from numpy import append,array
from numpy.random import normal
def armaGen(phi,theta,sigma,n,burnin=0,verbose=0):
    l=max(len(phi),len(theta))
    if(burnin==0):
      burnin=10*l # Burn-in elements!
    w=normal(0,sigma,n+burnin)
    ARMA=array([])
    s=0.0
    l=max(len(phi),len(theta))
    for i in range(n+burnin):
        if(i<l):
          ARMA=append(ARMA,w[i])
        else:
          s=0.0
          for j in range(len(phi)):
              s=s+phi[j]*ARMA[i-j-1]
          for j in range(len(theta)):
              s=s+theta[j]*w[i-j-1]
          ARMA=append(ARMA,s+w[i])
    if(verbose!=0):
      print 'Measured standard deviation: '+str(sqrt(var(w[burnin:])))
    return ARMA[burnin:]

In [34]:
phi=[0.4,0.3]
theta=[0.1,-0.3]
sigma=2.0
n=1000
burnin=500
x=armaGen(phi,theta,sigma,n,burnin)

In [38]:
#x=armaGen(phi,theta,sigma,n)
x=armaGen( phi=[0.6,0.2], theta=[0.3, -0.1], sigma=100.0, n=100 )
x

array([-270.99674129, -453.16265384, -384.44934999, -250.16661639,
       -226.34869158, -263.92335363, -171.01976639, -366.68910035,
       -221.24131142, -236.37815288, -179.589729  , -227.23714298,
       -178.09441325, -122.04111801,  -71.24361195,  -59.12028156,
       -102.02436929,   27.08779302,   55.25184311,   40.90907021,
         73.14873466,   94.84457445,  246.41064235,  405.7229561 ,
        170.67615773,   76.5802097 ,   53.09847409,  -57.82353312,
       -109.51305453, -166.68700559, -136.85547333,  -80.65166492,
         -7.05751366,  -83.60134635,  -23.49140244,  -51.11279711,
        -23.75516752, -204.401493  , -140.66918925, -201.91931248,
       -190.69339819,  -90.82375155, -176.31971969,  -56.27146754,
       -116.25367267,  -39.71051004,  126.48409312,  215.73932326,
        130.59523281,  323.0889931 ,  339.62582991,  217.65281986,
        156.22887781,  153.0038421 ,  166.74049113,  147.59527474,
         73.60980781, -100.34304418,  -38.55331384,   43.45832

In [16]:
import matplotlib.pyplot as plt
plt.xlabel("Time units")
plt.ylabel("ARMA(2,2) Series")
plt.plot(x,'-r') # This plots the series as a red line.
plt.plot(x,'or') # This plots the series as red points.
plt.show()

In [42]:
startDatetime = datetime.datetime.strptime("2015-01-01 09:00:00", '%Y-%m-%d %H:%M:%S')
currDateTime = datetime.datetime.strptime("2015-01-02 19:00:00", '%Y-%m-%d %H:%M:%S')

dayDiff = (currDateTime - startDatetime).days;
dayDiff

1

In [44]:
#!/usr/bin/python
#-*- coding: utf-8 -*-

## 랜덤한 센서 데이터 생성
## 파일명 : makeSensorData.py
import numpy 
import datetime


startStr = "2015-01-01 00:00:00"
sec = 1
N = 10000
outputFile = 'output.csv'

armaN = 100
MAX_NUM_PER_FUN = 10000

def armaGen(phi,theta,sigma,n,burnin=0,verbose=0):
    from numpy import append,array
    from numpy.random import normal
    l=max(len(phi),len(theta))
    if(burnin==0):
      burnin=10*l # Burn-in elements!
    w=normal(0,sigma,n+burnin)
    ARMA=array([])
    s=0.0
    l=max(len(phi),len(theta))
    for i in range(n+burnin):
        if(i<l):
          ARMA=append(ARMA,w[i])
        else:
          s=0.0
          for j in range(len(phi)):
              s=s+phi[j]*ARMA[i-j-1]
          for j in range(len(theta)):
              s=s+theta[j]*w[i-j-1]
          ARMA=append(ARMA,s+w[i])
    if(verbose!=0):
      print 'Measured standard deviation: '+str(sqrt(var(w[burnin:])))
    return ARMA[burnin:]


sensor01 = {'code':'1', 'desc': 'Temerature' ,'mu':1100, 'sigma': 50, 'distribute' : numpy.random.normal, 'arma': armaGen( phi=[0.6,0.2], theta=[0.2, -0.2], sigma=200.0, n=armaN ) }
sensor02 = {'code':'2', 'desc': 'Humidity'   ,'mu':62,   'sigma': 5,  'distribute' : numpy.random.normal, 'arma': armaGen( phi=[0.6,0.2], theta=[0.3, 0.2], sigma=15.0, n=armaN )  }
sensor03 = {'code':'3', 'desc': 'Speed'      ,'mu':225,  'sigma': 0,  'distribute' : numpy.random.poisson, 'arma': armaGen( phi=[0.6,0.2], theta=[0.1, -0.1], sigma=80.0, n=armaN )  }
sensor04 = {'code':'4', 'desc': 'Vibration'  ,'mu':550,  'sigma': 10, 'distribute' : numpy.random.normal, 'arma': armaGen( phi=[0.6,0.2], theta=[0.5, 0.1], sigma=200.0, n=armaN )  }
sensor05 = {'code':'5', 'desc': 'Pressure'   ,'mu':300,  'sigma': 400,'distribute' : numpy.random.uniform, 'arma': armaGen( phi=[0.6,0.2], theta=[0.3, -0.3], sigma=150.0, n=armaN )  }
sensor06 = {'code':'6', 'desc': 'Noise'      ,'mu':65,   'sigma': 10, 'distribute' : numpy.random.poisson, 'arma': armaGen( phi=[0.6,0.2], theta=[0.6, 0.1], sigma=10.0, n=armaN )  }
allSensor = list()
allSensor.append( sensor01 ) 
allSensor.append( sensor02 ) 
allSensor.append( sensor03 ) 
allSensor.append( sensor04 ) 
allSensor.append( sensor05 ) 
allSensor.append( sensor06 ) 

def randomDistribute( mean, sigma, size, distributeFun ) :
    """
    여러가지 분포에 따라서 인자 설정을 다르게 설정하도록 하는 함수
    """
    
    if "poisson" == distributeFun.__name__ : 
        return distributeFun( mean, size )
    else :
        return distributeFun( mean, sigma, size )

    
def makeSensorData( SensorList, startDatetime, currDateTime, sec, N, f ) :
    """ 여러가지 센서 정보를 인자로 받고 특정시점부터 데이터를 N개 생성하는 함수 정의
    SensorList : 센서 정보를 갖는 List, 센서 정보를 dictionary형식으로 정의함.
    currDateTime : 특정시점 
    sec : 시간 간격(초)
    N : 생성할 데이터의 개수
    """
    from cStringIO import StringIO
    strIO = StringIO()
    
    dayDiff = ((currDateTime - startDatetime).days) % armaN ;
    codeList = list()
    randNumList = list()
    for sensor in SensorList :
        codeList.append( sensor['code'] )
        rnum = randomDistribute( 
            sensor['mu'] + sensor['arma'][dayDiff ] , 
            sensor['sigma'], 
            N, 
            sensor['distribute']  ) 
        randNumList.append( rnum )

    for i in range( N ) :
        dateStr = currDateTime.strftime('%Y-%m-%d')
        timeStr = currDateTime.strftime('%H:%M:%S')
        for idx in range( len(codeList) ) : 
            strIO.write( "%s,%s,%s,%d\n" %( dateStr, timeStr, codeList[idx], randNumList[idx][i] )  )
            
        currDateTime = currDateTime + datetime.timedelta(seconds=sec)        
        
    f.write( strIO.getvalue() )
    f.flush()
    return currDateTime

def main(): 
    startDatetime = datetime.datetime.strptime(startStr, '%Y-%m-%d %H:%M:%S')
    nextDatetime = startDatetime
    
    with open(outputFile, 'w') as f:
        for i in range(  N / MAX_NUM_PER_FUN ) :
            n = MAX_NUM_PER_FUN
            if i == N / MAX_NUM_PER_FUN : 
                n = N % MAX_NUM_PER_FUN
            nextDatetime = makeSensorData( allSensor, startDatetime, nextDatetime, sec, n, f)

            
if __name__ == "__main__":
    import time
    t1 = time.time() # start time
    main()
    t2 = time.time() # end time
    print ("makeSensorData.py, Run Time: %dsec" %(t2-t1) )

makeSensorData.py, Run Time: 0sec
